version: "0.1"
server:
  port: 3000
  authentication:
    request-limit: 100mb
users:
  myapiuser: myStr@ngpa$$w0rd
sources:
  pg-clubdata-bookings:
    provider: postgres
    host: pg-clubdata-bookings
    port: 5432
    user: admin
    password: "123456"
    database: clubdata
  pg-clubdata-facilities:
    provider: postgres
    host: pg-clubdata-facilities
    port: 5432
    user: admin
    password: "123456"
    database: clubdata
  pg-clubdata-members:
    provider: postgres
    host: pg-clubdata-members
    port: 5432
    user: admin
    password: "123456"
    database: clubdata
schemas:
  clubdata:
    entities:
      members:
        source: pg-clubdata-members
        entity: members
      facilities:
        source: pg-clubdata-facilities
        entity: facilities
      bookings:
        source: pg-clubdata-bookings
        entity: bookings
