version: '2'
services:
  metal:
    build: ./sample/metal-server
    hostname: metal
    ports:
      - "3000:3000"
    volumes:
      - ./metal-server/config:/metal-server/config
      - ./metal-server/client:/metal-server/client
    depends_on:
      - mdb-mflix
      - ms-hr
      - pg-northwind
      - pg-clubdata
  mdb-mflix:
    image: mongo
    hostname: mdb-mflix
    ports:
      - "27017:27017"
    volumes:
      - ./mdb-mflix:/data/db
      - ./sample/mdb-mflix/sample_mflix:/mdb-mflix-samples
  ms-hr:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: ms-hr
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Azerty123!"
    volumes:
      - ./ms-hr:/var/opt/ms-hr
      - ./sample/ms-hr:/ms-hr-samples
  pg-northwind:
    image: postgres
    hostname: pg-northwind
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./pg-northwind:/var/lib/postgresql/data/pgdata
      - ./sample/pg-northwind:/pg-northwind-samples
  pg-clubdata:
    image: postgres
    hostname: pg-clubdata
    ports:
      - "5433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./pg-clubdata:/var/lib/postgresql/data/pgdata
      - ./sample/pg-clubdata:/pg-clubdata-samples
