version: '2'
services:
  metal:
    build: ./sample/metal-server
    hostname: metal
    ports:
      - "3000:3000"
    volumes:
      - ./metal-server/config:/metal-server/config
    depends_on:
      - mongodb
      - mssql
      - postgres1
      - postgres2
  mongodb:
    image: mongo
    hostname: mongodb
    volumes:
      - ./mongodb:/data/db
      - ./sample/mongodb/sample_mflix:/mongodb-samples
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Azerty123!"
    volumes:
      - ./mssql:/var/opt/mssql
      - ./sample/mssql:/mssql-samples
  postgres1:
    image: postgres
    hostname: postgres1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres1:/var/lib/postgresql/data/pgdata
      - ./sample/postgres1:/postgres1-samples
  postgres2:
    image: postgres
    hostname: postgres2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres2:/var/lib/postgresql/data/pgdata
      - ./sample/postgres2:/postgres2-samples
