##
# Dockerfile for Metal Server
# v0.1
##

FROM node:21
LABEL org.opencontainers.image.authors="Anis Megdiche <anis.megdiche@gmail.com>"

WORKDIR /

RUN git clone https://github.com/anismegdiche/metal-server.git

WORKDIR /metal-server

RUN \cp ./config/config-sample-docker.yml ./config/config.yml

RUN npm install
RUN npx tsc

EXPOSE 3000

CMD [ "npm", "run", "prod" ]
