##
# Dockerfile for Metal Server
# v0.3
##

FROM node:22.10.0
LABEL org.opencontainers.image.authors="Anis Megdiche <anis.megdiche@gmail.com>"

WORKDIR /

RUN git clone https://github.com/anismegdiche/metal-server.git

WORKDIR /metal-server

RUN \cp ./config/config-sample-docker.yml ./config/config.yml

RUN npm install --loglevel verbose

# typia
RUN npm run _typia-prepare

RUN npx tsc

EXPOSE 3000

CMD [ "npm", "run", "prod" ]
